### ISSUE TITLE
[Question]Is it possible to sync reading status in multi  device?

### ISSUE THREAD

**Issue by Quorafind** [joethei/obsidian-rss#17]
It will be nice to make rss sync through read.json?

**Comment by joethei** [comment]
Read status is already saved, so should also be synced as long as you have the data.json synced.
It should work as long as you don't have obsidian open on multiple devices at the same time, as the file gets only read
at startup.

**Comment by frvkl** [comment]
I am using Obsidian Sync and am syncing everything. Unfortunately, the read status does not seem to be synced to mobile. I love you are bringing a RSS reader into Obsidian, but in order to keep using this plugin, it will have to work on mobile as well. I hope you are able to solve this. Keep up the good work. :)

P.S. The 'Refresh Feeds' command does not seem to be working on mobile as well.

**Comment by frvkl** [comment]
Also on mobile, when I open an unread article, it remains on status 'unread', even after closing and reopening the mobile app.

**Comment by joethei** [comment]
The next update(will be released later today) will include a new setting you need to enable,
then all changes will show up within a minute.

This should keep resource usage low, and still have the desired effect.
