### ISSUE TITLE
New Feed Overwrites content of older one, refreshing feeds doesnt solve the issue

### ISSUE THREAD

**Issue by artjafri** [joethei/obsidian-rss#39]
I have two podcast feeds I tried to link. 99PI https://feeds.simplecast.com/BqbsxVfO and TAL: http://feed.thisamericanlife.org/talpodcast 
After inputting the second feed I found that the first folder got all of its content  replaced. Prior to adding TAL the 99PI feed was accurate to its release, with the latest entry being https://99percentinvisible.org/episode/cute-little-monstrosities-of-nature/ now all of its content is from TAL, with the only entry from 99 pi being the first entry in the feed, from 2010. oddly enough clicking the open in browser button on the link in 99PI is opening the most recent episode
![Screenshot 2021-11-24 160936](https://user-images.githubusercontent.com/36727668/143313161-e04bdc4e-aab2-4ebe-a8c7-05666ef3f1f9.jpg)
![Screenshot 2021-11-24 161006](https://user-images.githubusercontent.com/36727668/143313162-38f3c567-208e-44f6-b8c2-5a8af56a93a3.jpg)

**Comment by joethei** [comment]
which version of the plugin are you using?

**Comment by joethei** [comment]
This will be fixed with the next release,
The link of an entry for the 99% podcast is the same for all of them, this caused some weird behavior, because I previously used that to compare items when merging the old with the new data.


Also, somewhat unrelated, but you will get an audio player with the next release.
